# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/skuba/skuba_athome/gesture_detection

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/skuba/skuba_athome/gesture_detection

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/skuba/skuba_athome/gesture_detection/CMakeFiles /home/skuba/skuba_athome/gesture_detection/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/skuba/skuba_athome/gesture_detection/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NiHandTracker

# Build rule for target.
NiHandTracker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NiHandTracker
.PHONY : NiHandTracker

# fast build rule for target.
NiHandTracker/fast:
	$(MAKE) -f CMakeFiles/NiHandTracker.dir/build.make CMakeFiles/NiHandTracker.dir/build
.PHONY : NiHandTracker/fast

#=============================================================================
# Target rules for targets named ROSBUILD_genmsg_cpp

# Build rule for target.
ROSBUILD_genmsg_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROSBUILD_genmsg_cpp
.PHONY : ROSBUILD_genmsg_cpp

# fast build rule for target.
ROSBUILD_genmsg_cpp/fast:
	$(MAKE) -f CMakeFiles/ROSBUILD_genmsg_cpp.dir/build.make CMakeFiles/ROSBUILD_genmsg_cpp.dir/build
.PHONY : ROSBUILD_genmsg_cpp/fast

#=============================================================================
# Target rules for targets named ROSBUILD_genmsg_lisp

# Build rule for target.
ROSBUILD_genmsg_lisp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROSBUILD_genmsg_lisp
.PHONY : ROSBUILD_genmsg_lisp

# fast build rule for target.
ROSBUILD_genmsg_lisp/fast:
	$(MAKE) -f CMakeFiles/ROSBUILD_genmsg_lisp.dir/build.make CMakeFiles/ROSBUILD_genmsg_lisp.dir/build
.PHONY : ROSBUILD_genmsg_lisp/fast

#=============================================================================
# Target rules for targets named ROSBUILD_gensrv_cpp

# Build rule for target.
ROSBUILD_gensrv_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROSBUILD_gensrv_cpp
.PHONY : ROSBUILD_gensrv_cpp

# fast build rule for target.
ROSBUILD_gensrv_cpp/fast:
	$(MAKE) -f CMakeFiles/ROSBUILD_gensrv_cpp.dir/build.make CMakeFiles/ROSBUILD_gensrv_cpp.dir/build
.PHONY : ROSBUILD_gensrv_cpp/fast

#=============================================================================
# Target rules for targets named ROSBUILD_gensrv_lisp

# Build rule for target.
ROSBUILD_gensrv_lisp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROSBUILD_gensrv_lisp
.PHONY : ROSBUILD_gensrv_lisp

# fast build rule for target.
ROSBUILD_gensrv_lisp/fast:
	$(MAKE) -f CMakeFiles/ROSBUILD_gensrv_lisp.dir/build.make CMakeFiles/ROSBUILD_gensrv_lisp.dir/build
.PHONY : ROSBUILD_gensrv_lisp/fast

#=============================================================================
# Target rules for targets named clean-test-results

# Build rule for target.
clean-test-results: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-test-results
.PHONY : clean-test-results

# fast build rule for target.
clean-test-results/fast:
	$(MAKE) -f CMakeFiles/clean-test-results.dir/build.make CMakeFiles/clean-test-results.dir/build
.PHONY : clean-test-results/fast

#=============================================================================
# Target rules for targets named hand_tracker

# Build rule for target.
hand_tracker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hand_tracker
.PHONY : hand_tracker

# fast build rule for target.
hand_tracker/fast:
	$(MAKE) -f CMakeFiles/hand_tracker.dir/build.make CMakeFiles/hand_tracker.dir/build
.PHONY : hand_tracker/fast

#=============================================================================
# Target rules for targets named openni_tracker

# Build rule for target.
openni_tracker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openni_tracker
.PHONY : openni_tracker

# fast build rule for target.
openni_tracker/fast:
	$(MAKE) -f CMakeFiles/openni_tracker.dir/build.make CMakeFiles/openni_tracker.dir/build
.PHONY : openni_tracker/fast

#=============================================================================
# Target rules for targets named rosbuild_precompile

# Build rule for target.
rosbuild_precompile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rosbuild_precompile
.PHONY : rosbuild_precompile

# fast build rule for target.
rosbuild_precompile/fast:
	$(MAKE) -f CMakeFiles/rosbuild_precompile.dir/build.make CMakeFiles/rosbuild_precompile.dir/build
.PHONY : rosbuild_precompile/fast

#=============================================================================
# Target rules for targets named rosbuild_premsgsrvgen

# Build rule for target.
rosbuild_premsgsrvgen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rosbuild_premsgsrvgen
.PHONY : rosbuild_premsgsrvgen

# fast build rule for target.
rosbuild_premsgsrvgen/fast:
	$(MAKE) -f CMakeFiles/rosbuild_premsgsrvgen.dir/build.make CMakeFiles/rosbuild_premsgsrvgen.dir/build
.PHONY : rosbuild_premsgsrvgen/fast

#=============================================================================
# Target rules for targets named rospack_genmsg

# Build rule for target.
rospack_genmsg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rospack_genmsg
.PHONY : rospack_genmsg

# fast build rule for target.
rospack_genmsg/fast:
	$(MAKE) -f CMakeFiles/rospack_genmsg.dir/build.make CMakeFiles/rospack_genmsg.dir/build
.PHONY : rospack_genmsg/fast

#=============================================================================
# Target rules for targets named rospack_genmsg_libexe

# Build rule for target.
rospack_genmsg_libexe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rospack_genmsg_libexe
.PHONY : rospack_genmsg_libexe

# fast build rule for target.
rospack_genmsg_libexe/fast:
	$(MAKE) -f CMakeFiles/rospack_genmsg_libexe.dir/build.make CMakeFiles/rospack_genmsg_libexe.dir/build
.PHONY : rospack_genmsg_libexe/fast

#=============================================================================
# Target rules for targets named rospack_gensrv

# Build rule for target.
rospack_gensrv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rospack_gensrv
.PHONY : rospack_gensrv

# fast build rule for target.
rospack_gensrv/fast:
	$(MAKE) -f CMakeFiles/rospack_gensrv.dir/build.make CMakeFiles/rospack_gensrv.dir/build
.PHONY : rospack_gensrv/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test-future

# Build rule for target.
test-future: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-future
.PHONY : test-future

# fast build rule for target.
test-future/fast:
	$(MAKE) -f CMakeFiles/test-future.dir/build.make CMakeFiles/test-future.dir/build
.PHONY : test-future/fast

#=============================================================================
# Target rules for targets named test-results

# Build rule for target.
test-results: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-results
.PHONY : test-results

# fast build rule for target.
test-results/fast:
	$(MAKE) -f CMakeFiles/test-results.dir/build.make CMakeFiles/test-results.dir/build
.PHONY : test-results/fast

#=============================================================================
# Target rules for targets named test-results-run

# Build rule for target.
test-results-run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-results-run
.PHONY : test-results-run

# fast build rule for target.
test-results-run/fast:
	$(MAKE) -f CMakeFiles/test-results-run.dir/build.make CMakeFiles/test-results-run.dir/build
.PHONY : test-results-run/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

# target to build an object file
src/NiHandTracker/NiHandTracker.o:
	$(MAKE) -f CMakeFiles/NiHandTracker.dir/build.make CMakeFiles/NiHandTracker.dir/src/NiHandTracker/NiHandTracker.o
.PHONY : src/NiHandTracker/NiHandTracker.o

# target to preprocess a source file
src/NiHandTracker/NiHandTracker.i:
	$(MAKE) -f CMakeFiles/NiHandTracker.dir/build.make CMakeFiles/NiHandTracker.dir/src/NiHandTracker/NiHandTracker.i
.PHONY : src/NiHandTracker/NiHandTracker.i

# target to generate assembly for a file
src/NiHandTracker/NiHandTracker.s:
	$(MAKE) -f CMakeFiles/NiHandTracker.dir/build.make CMakeFiles/NiHandTracker.dir/src/NiHandTracker/NiHandTracker.s
.PHONY : src/NiHandTracker/NiHandTracker.s

# target to build an object file
src/NiHandTracker/NiHandViewer.o:
	$(MAKE) -f CMakeFiles/NiHandTracker.dir/build.make CMakeFiles/NiHandTracker.dir/src/NiHandTracker/NiHandViewer.o
.PHONY : src/NiHandTracker/NiHandViewer.o

# target to preprocess a source file
src/NiHandTracker/NiHandViewer.i:
	$(MAKE) -f CMakeFiles/NiHandTracker.dir/build.make CMakeFiles/NiHandTracker.dir/src/NiHandTracker/NiHandViewer.i
.PHONY : src/NiHandTracker/NiHandViewer.i

# target to generate assembly for a file
src/NiHandTracker/NiHandViewer.s:
	$(MAKE) -f CMakeFiles/NiHandTracker.dir/build.make CMakeFiles/NiHandTracker.dir/src/NiHandTracker/NiHandViewer.s
.PHONY : src/NiHandTracker/NiHandViewer.s

# target to build an object file
src/NiHandTracker/NiSimpleViewer.o:
	$(MAKE) -f CMakeFiles/NiHandTracker.dir/build.make CMakeFiles/NiHandTracker.dir/src/NiHandTracker/NiSimpleViewer.o
.PHONY : src/NiHandTracker/NiSimpleViewer.o

# target to preprocess a source file
src/NiHandTracker/NiSimpleViewer.i:
	$(MAKE) -f CMakeFiles/NiHandTracker.dir/build.make CMakeFiles/NiHandTracker.dir/src/NiHandTracker/NiSimpleViewer.i
.PHONY : src/NiHandTracker/NiSimpleViewer.i

# target to generate assembly for a file
src/NiHandTracker/NiSimpleViewer.s:
	$(MAKE) -f CMakeFiles/NiHandTracker.dir/build.make CMakeFiles/NiHandTracker.dir/src/NiHandTracker/NiSimpleViewer.s
.PHONY : src/NiHandTracker/NiSimpleViewer.s

# target to build an object file
src/NiHandTracker/NiTrailHistory.o:
	$(MAKE) -f CMakeFiles/NiHandTracker.dir/build.make CMakeFiles/NiHandTracker.dir/src/NiHandTracker/NiTrailHistory.o
.PHONY : src/NiHandTracker/NiTrailHistory.o

# target to preprocess a source file
src/NiHandTracker/NiTrailHistory.i:
	$(MAKE) -f CMakeFiles/NiHandTracker.dir/build.make CMakeFiles/NiHandTracker.dir/src/NiHandTracker/NiTrailHistory.i
.PHONY : src/NiHandTracker/NiTrailHistory.i

# target to generate assembly for a file
src/NiHandTracker/NiTrailHistory.s:
	$(MAKE) -f CMakeFiles/NiHandTracker.dir/build.make CMakeFiles/NiHandTracker.dir/src/NiHandTracker/NiTrailHistory.s
.PHONY : src/NiHandTracker/NiTrailHistory.s

# target to build an object file
src/NiHandTracker/main.o:
	$(MAKE) -f CMakeFiles/NiHandTracker.dir/build.make CMakeFiles/NiHandTracker.dir/src/NiHandTracker/main.o
.PHONY : src/NiHandTracker/main.o

# target to preprocess a source file
src/NiHandTracker/main.i:
	$(MAKE) -f CMakeFiles/NiHandTracker.dir/build.make CMakeFiles/NiHandTracker.dir/src/NiHandTracker/main.i
.PHONY : src/NiHandTracker/main.i

# target to generate assembly for a file
src/NiHandTracker/main.s:
	$(MAKE) -f CMakeFiles/NiHandTracker.dir/build.make CMakeFiles/NiHandTracker.dir/src/NiHandTracker/main.s
.PHONY : src/NiHandTracker/main.s

# target to build an object file
src/hand_tracker.o:
	$(MAKE) -f CMakeFiles/hand_tracker.dir/build.make CMakeFiles/hand_tracker.dir/src/hand_tracker.o
.PHONY : src/hand_tracker.o

# target to preprocess a source file
src/hand_tracker.i:
	$(MAKE) -f CMakeFiles/hand_tracker.dir/build.make CMakeFiles/hand_tracker.dir/src/hand_tracker.i
.PHONY : src/hand_tracker.i

# target to generate assembly for a file
src/hand_tracker.s:
	$(MAKE) -f CMakeFiles/hand_tracker.dir/build.make CMakeFiles/hand_tracker.dir/src/hand_tracker.s
.PHONY : src/hand_tracker.s

# target to build an object file
src/openni_tracker.o:
	$(MAKE) -f CMakeFiles/openni_tracker.dir/build.make CMakeFiles/openni_tracker.dir/src/openni_tracker.o
.PHONY : src/openni_tracker.o

# target to preprocess a source file
src/openni_tracker.i:
	$(MAKE) -f CMakeFiles/openni_tracker.dir/build.make CMakeFiles/openni_tracker.dir/src/openni_tracker.i
.PHONY : src/openni_tracker.i

# target to generate assembly for a file
src/openni_tracker.s:
	$(MAKE) -f CMakeFiles/openni_tracker.dir/build.make CMakeFiles/openni_tracker.dir/src/openni_tracker.s
.PHONY : src/openni_tracker.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... NiHandTracker"
	@echo "... ROSBUILD_genmsg_cpp"
	@echo "... ROSBUILD_genmsg_lisp"
	@echo "... ROSBUILD_gensrv_cpp"
	@echo "... ROSBUILD_gensrv_lisp"
	@echo "... clean-test-results"
	@echo "... edit_cache"
	@echo "... hand_tracker"
	@echo "... openni_tracker"
	@echo "... rebuild_cache"
	@echo "... rosbuild_precompile"
	@echo "... rosbuild_premsgsrvgen"
	@echo "... rospack_genmsg"
	@echo "... rospack_genmsg_libexe"
	@echo "... rospack_gensrv"
	@echo "... test"
	@echo "... test-future"
	@echo "... test-results"
	@echo "... test-results-run"
	@echo "... tests"
	@echo "... src/NiHandTracker/NiHandTracker.o"
	@echo "... src/NiHandTracker/NiHandTracker.i"
	@echo "... src/NiHandTracker/NiHandTracker.s"
	@echo "... src/NiHandTracker/NiHandViewer.o"
	@echo "... src/NiHandTracker/NiHandViewer.i"
	@echo "... src/NiHandTracker/NiHandViewer.s"
	@echo "... src/NiHandTracker/NiSimpleViewer.o"
	@echo "... src/NiHandTracker/NiSimpleViewer.i"
	@echo "... src/NiHandTracker/NiSimpleViewer.s"
	@echo "... src/NiHandTracker/NiTrailHistory.o"
	@echo "... src/NiHandTracker/NiTrailHistory.i"
	@echo "... src/NiHandTracker/NiTrailHistory.s"
	@echo "... src/NiHandTracker/main.o"
	@echo "... src/NiHandTracker/main.i"
	@echo "... src/NiHandTracker/main.s"
	@echo "... src/hand_tracker.o"
	@echo "... src/hand_tracker.i"
	@echo "... src/hand_tracker.s"
	@echo "... src/openni_tracker.o"
	@echo "... src/openni_tracker.i"
	@echo "... src/openni_tracker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

